In [2]:
import pandas as pd
import numpy as np
from scipy import stats
import random

pd.set_option('max_columns', 81)
pd.set_option('max_rows', 81)

df = pd.read_csv('../cleaned_datasets/train_cleaned.csv')
df.head()

,LotArea,TotalBsmtSF,1stFlrSF,GrLivArea,SalePrice,RegularLotShape,LandIsLvl,LotConfigCL,LotAdjacencyType,HouseCondition,YrBuilt,WasRemodeled,VeneerType,HeatingQuality,EleSystem,BsmtHasBath,HasHalfBath,Bedrooms,RemainingRooms,AdditionalRooms,NumFireplaces,GarageAreaByCar,HasDeck,HasPool,MonthSold,YearSold
0,8450,856,856,1710,208500,1,1,0,0,2,1,0,1,0,0,1,1,2,5,3,0,2,0,0,1,2
1,9600,1262,1262,1262,181500,1,1,3,1,1,1,0,0,0,0,1,0,2,3,1,1,2,1,0,4,1
2,11250,920,920,1786,223500,0,1,0,0,2,1,1,1,0,0,1,1,2,3,1,1,2,0,0,8,2
3,9550,756,961,1717,140000,0,1,1,0,2,0,1,0,2,0,1,0,2,4,2,1,3,0,0,1,0
4,14260,1145,1145,2198,250000,0,1,3,0,2,1,0,1,0,0,1,1,3,5,3,1,3,1,0,11,2

In [3]:
df.drop(columns=['TotalBsmtSF', 'RemainingRooms'], inplace=True)

In [4]:
from pandas_profiling import ProfileReport

profile = ProfileReport(df, title='Cleaned Dataset', explorative=True)

In [5]:
profile.to_widgets()

HBox(children=(FloatProgress(value=0.0, description='Summarize dataset', max=38.0, style=ProgressStyle(descripâ€¦

HBox(children=(FloatProgress(value=0.0, description='Generate report structure', max=1.0, style=ProgressStyle(â€¦

HBox(children=(FloatProgress(value=0.0, description='Render widgets', max=1.0, style=ProgressStyle(descriptionâ€¦

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valuâ€¦

In [5]:
df.head()

,LotArea,1stFlrSF,GrLivArea,SalePrice,RegularLotShape,LandIsLvl,LotConfigCL,LotAdjacencyType,HouseCondition,YrBuilt,WasRemodeled,VeneerType,HeatingQuality,EleSystem,BsmtHasBath,HasHalfBath,Bedrooms,AdditionalRooms,NumFireplaces,GarageAreaByCar,HasDeck,HasPool,MonthSold,YearSold
0,8450,856,1710,208500,1,1,0,0,2,1,0,1,0,0,1,1,2,3,0,2,0,0,1,2
1,9600,1262,1262,181500,1,1,3,1,1,1,0,0,0,0,1,0,2,1,1,2,1,0,4,1
2,11250,920,1786,223500,0,1,0,0,2,1,1,1,0,0,1,1,2,1,1,2,0,0,8,2
3,9550,961,1717,140000,0,1,1,0,2,0,1,0,2,0,1,0,2,2,1,3,0,0,1,0
4,14260,1145,2198,250000,0,1,3,0,2,1,0,1,0,0,1,1,3,3,1,3,1,0,11,2

In [14]:
df.columns

Index(['LotArea', '1stFlrSF', 'GrLivArea', 'SalePrice', 'RegularLotShape',
       'LandIsLvl', 'LotConfigCL', 'LotAdjacencyType', 'HouseCondition',
       'YrBuilt', 'WasRemodeled', 'VeneerType', 'HeatingQuality', 'EleSystem',
       'BsmtHasBath', 'HasHalfBath', 'Bedrooms', 'AdditionalRooms',
       'NumFireplaces', 'GarageAreaByCar', 'HasDeck', 'HasPool', 'MonthSold',
       'YearSold'],
      dtype='object')

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

feat_list = list(df.columns)
feat_list.remove('SalePrice')

y = df['SalePrice']
X = df[feat_list]

X_remain, X_test, y_remain, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_remain, y_remain, test_size=0.25, random_state=42)

print(f'X_train: {X_train.shape} - X_val: {X_val.shape} - X_test: {X_test.shape}')
print(f'y_train: {y_train.shape} - y_val: {y_val.shape} - y_test: {y_test.shape}')

X_train: (751, 23) - X_val: (251, 23) - X_test: (251, 23)
y_train: (751,) - y_val: (251,) - y_test: (251,)

In [23]:
lr = LinearRegression()

lr.fit(X_train, y_train)

print(f'Validation Score: {lr.score(X_val, y_val)}')
print(f'Test Score: {lr.score(X_test, y_test)}')

Validation Score: 0.7941694571364838
Test Score: 0.7964756721996041

In [24]:
test = pd.read_csv('../test.csv')
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [26]:
df1 = test.copy()

condition0 = (len(df1) * 0.1)
cols = df1.columns

for col in cols:
    n_NaN = (df1[col].isna().sum())
    if n_NaN > condition0:
        df1.drop(columns=col, inplace=True)
    elif 0 < n_NaN < condition0:
        if df1[col].dtype != 'O':
            if len(df1[col].unique()) > 20:
                df1[col].fillna(value=df1[col].mean(), inplace=True)
            else:
                df1[col].fillna(value=df1[col].mode()[0], inplace=True)
        else:
            df1[col].fillna(value=df1[col].mode()[0], inplace=True)

In [39]:
cleaned = df1.copy()

In [40]:
# # Work to be done for some_work columns
# # ==========================================================

# # Start with the numeric columns filtering out the outliers (> 95-Percentiles)

# # 1. LotArea > 95-percentile (17401.15 ftsq)
# condition_LotArea = (cleaned['LotArea'] <= 17401.15)

# # 2. TotalBsmtSF > 1753
# condition_TotalBsmtSF = (cleaned['TotalBsmtSF'] <= 1753)

# # 3. 1stFlrSF > 1831.25
# condition_1stFlrSF = (cleaned['1stFlrSF'] <= 1831.25)

# # 4. GrLivArea > 2466.1
# condition_GrLivArea = (cleaned['GrLivArea'] <= 2466.1)


# ==========================================================

# Next, columnal consolidation

# 1. LotShape - (Combine Irregular)
cleaned.loc[cleaned['LotShape'].str.startswith('IR'), 'RegularLotShape'] = 0
cleaned.loc[cleaned['LotShape'].str.startswith('Reg'), 'RegularLotShape'] = 1

# 2. LandContour - (Combine non Lvl values)
cleaned.loc[(cleaned['LandContour'] == 'Bnk') | (cleaned['LandContour'] == 'HLS') | (cleaned['LandContour'] == 'Low'), 'LandIsLvl'] = 0
cleaned.loc[cleaned['LandContour'] == 'Lvl', 'LandIsLvl'] = 1

# 3. LotConfig - (FR2, FR3 essentially the same)
# Ordinality - {'Inside': 0, 'Corner': 1, 'CulDSac': 2, 'FR': 3}
cleaned.loc[cleaned['LotConfig'] == 'Inside', 'LotConfigCL'] = 0
cleaned.loc[cleaned['LotConfig'] == 'Corner', 'LotConfigCL'] = 1
cleaned.loc[cleaned['LotConfig'] == 'CulDSac', 'LotConfigCL'] = 2
cleaned.loc[cleaned['LotConfig'].str.startswith('FR'), 'LotConfigCL'] = 3

# 4. Condition1 - (Combine adjacency types)
# Ordinality - {'Norm': 0, 'Feedr/Artery': 1, 'RRA/N': 2, 'PosFeat': 3}
cleaned.loc[cleaned['Condition1'] == 'Norm', 'LotAdjacencyType'] = 0
cleaned.loc[(cleaned['Condition1'] == 'Feedr') | (cleaned['Condition1'] == 'Artery'), 'LotAdjacencyType'] = 1
cleaned.loc[cleaned['Condition1'].str.startswith('RR'), 'LotAdjacencyType'] = 2
cleaned.loc[cleaned['Condition1'].str.startswith('Pos'), 'LotAdjacencyType'] = 3

# 5. OverallQual - (Combine extremes)
# Ordinality - {'below_4': 0, 'Average(4,5,6)': 1, 'above_6': 2}
cleaned.loc[cleaned['OverallQual'] < 4, 'HouseCondition'] = 0
cleaned.loc[cleaned['OverallQual'] <= 6, 'HouseCondition'] = 1
cleaned.loc[cleaned['OverallQual'] >= 7, 'HouseCondition'] = 2

# 6. YearBuilt - Split {MadeBefore1946: 0, MadeAfter1946: 1}
cleaned.loc[cleaned['YearBuilt'] < 1946, 'YrBuilt'] = 0
cleaned.loc[cleaned['YearBuilt'] >= 1946, 'YrBuilt'] = 1

# 7. YearRemodAdd - NEW COLUMN - WasRemodeled
# Process - If the years for YearBuilt and YearRemodAdd are the same, there was no remodel
cleaned.loc[cleaned['YearBuilt'] == cleaned['YearRemodAdd'], 'WasRemodeled'] = 0
cleaned.loc[cleaned['YearBuilt'] != cleaned['YearRemodAdd'], 'WasRemodeled'] = 1

# 8. MasVnrType - (Combine brick-types)
# Ordinality - {'None': 0, 'Brick': 1, 'Stone': 3}
cleaned.loc[cleaned['MasVnrType'] == 'None', 'VeneerType'] = 0
cleaned.loc[cleaned['MasVnrType'].str.startswith('Brk'), 'VeneerType'] = 1
cleaned.loc[cleaned['MasVnrType'] == 'Stone', 'VeneerType'] = 2

# 9. HeatingQC - (Combine Fair and Poor - heating is important!)
# Ordinality - {'Excellent': 0, 'Average': 1, 'Good': 2, 'Poor': 3}
cleaned.loc[cleaned['HeatingQC'] == 'Ex', 'HeatingQuality'] = 0
cleaned.loc[cleaned['HeatingQC'] == 'TA', 'HeatingQuality'] = 1
cleaned.loc[cleaned['HeatingQC'] == 'Gd', 'HeatingQuality'] = 2
cleaned.loc[(cleaned['HeatingQC'] == 'Fa') | (cleaned['HeatingQC'] == 'Po'), 'HeatingQuality'] = 3

# 10. Electrical - (Combine all Fuse types)
# Binary - {'Breaker': 0, 'Fuse': 1}
cleaned.loc[cleaned['Electrical'] == 'SBrkr', 'EleSystem'] = 0
cleaned.loc[(cleaned['Electrical'].str.startswith('Fuse')) | (cleaned['Electrical'] == 'Mix'), 'EleSystem'] = 1

# 11. BsmtFull/HalfBath - NEW COLUMN - BsmtHasBath
cleaned.loc[(cleaned['BsmtFullBath'] == 0) | (cleaned['BsmtHalfBath'] == 0), 'BsmtHasBath'] = 0
cleaned.loc[(cleaned['BsmtFullBath'] > 0) | (cleaned['BsmtHalfBath'] > 0), 'BsmtHasBath'] = 1

# 12. HalfBath - (Combine 1 and 2 to make binary) - HasHalfBath
cleaned.loc[cleaned['HalfBath'] == 0, 'HasHalfBath'] = 0
cleaned.loc[cleaned['HalfBath'] > 0, 'HasHalfBath'] = 1

# 13. BedroomAbvGr - (0-1, 2, 3, 4+)
# Ordinality - {'less_than_2': 0, '2': 1, '3': 2, '4+': 3}
cleaned.loc[cleaned['BedroomAbvGr'] < 2, 'Bedrooms'] = 0
cleaned.loc[cleaned['BedroomAbvGr'] == 2, 'Bedrooms'] = 1
cleaned.loc[cleaned['BedroomAbvGr'] == 3, 'Bedrooms'] = 2
cleaned.loc[cleaned['BedroomAbvGr'] > 3, 'Bedrooms'] = 3

# 14. TotRmsAvbGrd - NEW COLUMN - AdditionalRooms
# Make a new column called RemainingRooms that is the difference between Total Rooms and Bedrooms
# Ordinality - {'less_than_3': 0, '3': 1, '4': 2, '5': 3, 'more_than_5': 4}
cleaned['RemainingRooms'] = cleaned['TotRmsAbvGrd'] - cleaned['BedroomAbvGr']
cleaned.loc[cleaned['RemainingRooms'] < 3, 'AdditionalRooms'] = 0
cleaned.loc[cleaned['RemainingRooms'] == 3, 'AdditionalRooms'] = 1
cleaned.loc[cleaned['RemainingRooms'] == 4, 'AdditionalRooms'] = 2
cleaned.loc[cleaned['RemainingRooms'] == 5, 'AdditionalRooms'] = 3
cleaned.loc[cleaned['RemainingRooms'] > 5, 'AdditionalRooms'] = 4

# 15. Fireplaces - (Combine 2 and 3)
# Ordinality - {'None': 0, '1': 1, '2+': 2}
cleaned.loc[cleaned['Fireplaces'] == 0, 'NumFireplaces'] = 0
cleaned.loc[cleaned['Fireplaces'] == 1, 'NumFireplaces'] = 1
cleaned.loc[cleaned['Fireplaces'] > 1, 'NumFireplaces'] = 2

# 16. GarageCars - (Combine 3 and 4)
# Ordinality - {'0': 0, '1': 1, '2': 2, '3+': 3}
cleaned.loc[cleaned['GarageCars'] == 0, 'GarageAreaByCar'] = 0
cleaned.loc[cleaned['GarageCars'] == 1, 'GarageAreaByCar'] = 1
cleaned.loc[cleaned['GarageCars'] == 2, 'GarageAreaByCar'] = 2
cleaned.loc[cleaned['GarageCars'] > 2, 'GarageAreaByCar'] = 3

# 17. WoodDeckSF - NEW COLUMN - HasDeck
cleaned.loc[cleaned['WoodDeckSF'] == 0, 'HasDeck'] = 0
cleaned.loc[cleaned['WoodDeckSF'] > 0, 'HasDeck'] = 1

# 18. PoolArea - NEW COLUMN - HasPool
cleaned.loc[cleaned['PoolArea'] == 0, 'HasPool'] = 0
cleaned.loc[cleaned['PoolArea'] > 0, 'HasPool'] = 1

# 19. MoSold - Subtract all items by 1
# Ordinality - {'Jan': 0 ... 'Dec': 11}
cleaned['MonthSold'] = cleaned['MoSold'] - 1

# 20. YrSold - Convert years to 0-4 - 2010 might not have concluded at creation of dataset
# Ordinality - {'2006': 0, '2007': 1, '2008': 2, '2009': 3, '2010': 4}
cleaned.loc[cleaned['YrSold'] <= 2006, 'YearSold'] = 0
cleaned.loc[cleaned['YrSold'] == 2007, 'YearSold'] = 1
cleaned.loc[cleaned['YrSold'] == 2008, 'YearSold'] = 2
cleaned.loc[cleaned['YrSold'] == 2009, 'YearSold'] = 3
cleaned.loc[cleaned['YrSold'] == 2010, 'YearSold'] = 4

In [31]:
new_columns = list(cleaned.columns[-21:])

In [32]:
features_encoded = cleaned[new_columns].astype('int64')

In [41]:
df_inter = pd.concat([cleaned[['Id', 'LotArea', 'TotalBsmtSF', '1stFlrSF', 'GrLivArea']], features_encoded], axis=1)

In [42]:
df_inter.head()

,Id,LotArea,TotalBsmtSF,1stFlrSF,GrLivArea,RegularLotShape,LandIsLvl,LotConfigCL,LotAdjacencyType,HouseCondition,YrBuilt,WasRemodeled,VeneerType,HeatingQuality,EleSystem,BsmtHasBath,HasHalfBath,Bedrooms,RemainingRooms,AdditionalRooms,NumFireplaces,GarageAreaByCar,HasDeck,HasPool,MonthSold,YearSold
0,1461,11622,882.0,896,896,1,1,0,1,1,1,0,0,1,0,0,0,1,3,1,0,1,1,0,5,4
1,1462,14267,1329.0,1329,1329,0,1,1,0,1,1,0,1,1,0,0,1,2,3,1,0,1,1,0,5,4
2,1463,13830,928.0,928,1629,0,1,0,0,1,1,1,0,2,0,0,1,2,3,1,1,2,1,0,2,4
3,1464,9978,926.0,926,1604,0,1,0,0,1,1,0,1,0,0,0,1,2,4,2,1,2,1,0,5,4
4,1465,5005,1280.0,1280,1280,0,0,0,0,2,1,0,0,0,0,0,0,1,3,1,0,2,0,0,0,4

In [44]:
df_inter.drop(columns=['TotalBsmtSF', 'RemainingRooms'], inplace=True)

In [45]:
df_inter.head()

,Id,LotArea,1stFlrSF,GrLivArea,RegularLotShape,LandIsLvl,LotConfigCL,LotAdjacencyType,HouseCondition,YrBuilt,WasRemodeled,VeneerType,HeatingQuality,EleSystem,BsmtHasBath,HasHalfBath,Bedrooms,AdditionalRooms,NumFireplaces,GarageAreaByCar,HasDeck,HasPool,MonthSold,YearSold
0,1461,11622,896,896,1,1,0,1,1,1,0,0,1,0,0,0,1,1,0,1,1,0,5,4
1,1462,14267,1329,1329,0,1,1,0,1,1,0,1,1,0,0,1,2,1,0,1,1,0,5,4
2,1463,13830,928,1629,0,1,0,0,1,1,1,0,2,0,0,1,2,1,1,2,1,0,2,4
3,1464,9978,926,1604,0,1,0,0,1,1,0,1,0,0,0,1,2,2,1,2,1,0,5,4
4,1465,5005,1280,1280,0,0,0,0,2,1,0,0,0,0,0,0,1,1,0,2,0,0,0,4

In [48]:
IDs = df_inter['Id']

X = df_inter[df_inter.columns[1:]]

y_pred = lr.predict(X)

In [50]:
assert(len(IDs) == len(y_pred))

In [51]:
submission_cleaned = pd.DataFrame({'Id': IDs, 'SalePrice': y_pred})
submission_cleaned.head()

     Id      SalePrice
0  1461  113917.272939
1  1462  159922.397831
2  1463  172766.066459
3  1464  178176.618467
4  1465  174065.967069

In [52]:
submission_cleaned.tail()

        Id      SalePrice
1454  2915   81364.941464
1455  2916   95445.746708
1456  2917  187625.980203
1457  2918  116370.716001
1458  2919  247244.572399

In [53]:
# submission_cleaned.to_csv('../kaggle_submissions/cleaned_submission0.csv', index=False)

In [54]:
# Find X_val, X_test predictions and check against y_true for Root Mean Squared Logarithmic Error
from sklearn.metrics import mean_squared_log_error


y_pred_val = lr.predict(X_val)
y_pred_test = lr.predict(X_test)

val_rmsle = np.sqrt(mean_squared_log_error(y_val, y_pred_val))
test_rmsle = np.sqrt(mean_squared_log_error(y_test, y_pred_test))

print(f'Validation RMSlogE: {val_rmsle}')
print(f'Test RMSlogE: {test_rmsle}')

Validation RMSlogE: 0.1685681872346261
Test RMSlogE: 0.16517746136739062

In [56]:
# The above submission yielded a 0.20497 for RMSLE on Kaggle which is...

error_from_kaggle = 0.20497 - ((val_rmsle + test_rmsle)/2)
print(error_from_kaggle, 'away from the Kaggle submission score.')

0.03809717569899165 away from the Kaggle submission score.